name: NPM Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  node-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" | tee -a $GITHUB_ENV
          echo "package_version=${GITHUB_REF#refs/*/v}" | tee -a $GITHUB_ENV
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set version
        run: node ./.ci/node-set-version.js --package-json packages/core/package.json ${{ env.package_version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn workspace vue-mqtt-client build
      - name: Publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn workspace vue-mqtt-client npm publish --access=public --tag=next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
